// What is Encapsulation?

// Encapsulation is one of the fundamental concepts is object-oriented programming(OOP). It describes the idea of bundling data and methods that work on that data within one unit...